title: Main
actions:
- !writeStatus: {status: 'Installing Drivers'}
- !task: {path: 'Tasks\drivers.yml'}
- !writeStatus: {status: 'Installing Steam'}
- !task: {path: 'Tasks\steam.yml'}
- !writeStatus: {status: 'Creating shortcuts'}
- !task: {path: 'Tasks\shortcuts.yml'}
- !writeStatus: {status: 'Installing Steam Deck Tools',  option: "yesdecktools"}
- !task: {path: 'Tasks\steamdecktools.yml',  option: "yesdecktools"}
- !writeStatus: {status: 'Removing Password',  option: "removepassword"}
- !task: {path: 'Tasks\password.yml',  option: "removepassword"}
- !writeStatus: {status: 'Setting up gaming mode boot',  option: "yesgamingmode"}
- !task: {path: 'Tasks\gamingmode.yml',  option: "yesgamingmode"}