title: Main
actions:
  - !writeStatus: {status: 'Installing Drivers'}
  - !task: {path: 'Tasks\installers\drivers.yml'}
  - !writeStatus: {status: 'Installing Steam'}
  - !task: {path: 'Tasks\installers\steam.yml'}
  - !writeStatus: {status: 'Creating shortcuts'}
  - !task: {path: 'Tasks\tweaks\shortcuts.yml'}
  - !writeStatus: {status: 'Installing Steam Deck Tools',  option: "yesdecktools"}
  - !task: {path: 'Tasks\installers\steamdecktools.yml',  option: "yesdecktools"}
  - !writeStatus: {status: 'Removing Password',  option: "removepassword"}
  - !task: {path: 'Tasks\tweaks\password.yml',  option: "removepassword"}
  #- !writeStatus: {status: 'Setting up gaming mode boot',  option: "yesgamingmode"}
  #- !task: {path: 'Tasks\tweaks\gamingmode.yml',  option: "yesgamingmode"}
  - !writeStatus: {status: 'Performing General Optimizations'}
  - !task: {path: 'Tasks\tweaks\generaloptimizations.yml'}