title: Main
actions:
  - !writeStatus: {status: 'Creating DeckXP Folder'}
  - !powerShell: {command: '.\Scripts\createdeckxpfolder.ps1', exeDir: true, runas: currentUserElevated, wait: true}

  - !writeStatus: {status: 'Installing Drivers', option: "steamdecklcd"}
  - !task: {path: 'Tasks\installers\LCD\drivers.yml', option: "steamdecklcd"}

  - !writeStatus: {status: 'Installing Drivers', option: "steamdeckoled"}
  - !task: {path: 'Tasks\installers\OLED\drivers.yml', option: "steamdeckoled"}

  - !writeStatus: {status: 'Installing Steam'}
  - !task: {path: 'Tasks\installers\steam.yml'}

  - !writeStatus: {status: 'Creating shortcuts'}
  - !task: {path: 'Tasks\tweaks\shortcuts.yml'}

  - !writeStatus: {status: 'Installing DeckXP Toolbox'}
  - !task: {path: 'Tasks\installers\toolbox.yml'}

  - !writeStatus: {status: 'Removing Password',  option: "removepassword"}
  - !task: {path: 'Tasks\tweaks\password.yml',  option: "removepassword"}

  - !writeStatus: {status: 'Setting up gaming mode boot',  option: "yesgamingmode"}
  - !task: {path: 'Tasks\tweaks\gamingmode.yml',  option: "yesgamingmode"}

  - !writeStatus: {status: 'Performing General Optimizations'}
  - !task: {path: 'Tasks\tweaks\generaloptimizations.yml'}

  - !writeStatus: {status: 'Setting up Post-Install script'}
  - !run: {exe: 'Scripts\setup-postinstall.ps1', runas: currentUserElevated, exeDir: true, wait: true}