title: General Optimizations
actions:
  - !writeStatus: {status: 'Setting Time Zone to UTC'}
  - !registryValue: {path: 'HKLM\SOFTWARE\System\CurrentControlSet\Control\TimeZoneInformation', value: 'RealTimeIsUniversal', data: '1', type: REG_DWORD}

  - !writeStatus: {status: 'Disabling Hibernation'}
  - !cmd:
    command: powercfg -h off
    wait: true

  - !writeStatus: {status: 'Setting Display Scale to 100%'}
  - !powerShell:
    command: ./setdisplayscale.ps1
    exeDir: true
    wait: true

  - !writeStatus: {status: 'Replacing On-Screen Keyboard'}
  - !cmd:
    command: curl -L -o "%TEMP%\ReplaceOSK.bat" "https://github.com/Lulech23/ReplaceOSK/releases/download/v2.4-5/ReplaceOSK.bat"
    wait: true
  - !run: {exe: '%temp%\ReplaceOSK.bat', wait: true}
  - !file: {path: '%temp%\ReplaceOSK.bat'}

  - !writeStatus: {status: 'Installing Visual C++'}
  - !cmd:
    command: curl -L -o "%TEMP%\VisualCppRedist_AIO_x86_x64.exe" "https://github.com/abbodi1406/vcredist/releases/download/v0.83.0/VisualCppRedist_AIO_x86_x64.exe"
    wait: true
  - !run: {exe: '%temp%\VisualCppRedist_AIO_x86_x64.exe', args: '/ai /gm2', wait: true}
  - !file: {path: '%temp%\VisualCppRedist_AIO_x86_x64.exe'}

  - !writeStatus: {status: 'Installing DirectX'}
  - !cmd:
    command: curl -L -o "%TEMP%\dxwebsetup.exe" "https://download.microsoft.com/download/1/7/1/1718CCC4-6315-4D8E-9543-8E28A4E18C4C/dxwebsetup.exe"
    wait: true
  - !run: {exe: '%temp%\dxwebsetup.exe', args: '/silent', wait: true}
  - !file: {path: '%temp%\dxwebsetup.exe'}

  - !writeStatus: {status: 'Disabling Windows Feature Updates'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate', value: 'TargetReleaseVersion', data: '1', type: REG_DWORD}
  - !powerShell:
    command: 'if ((Get-CimInstance -Class Win32_OperatingSystem).Caption -match 11) {$a = ''Windows 11''} else {$a = ''Windows 10''}; New-ItemProperty -Path ''HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate'' -Name ''ProductVersion'' -Value $a -PropertyType String -Force'
    wait: true
  - !powerShell:
    command: '$ver = (Get-ItemProperty ''HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion'').DisplayVersion; New-ItemProperty -Path ''HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate'' -Name ''TargetReleaseVersion'' -Value $ver -PropertyType String -Force'
    wait: true

  - !writeStatus: {status: 'Setting Display To Landscape'}
  - !powerShell:
    command: ./setdisplaytolandscape.ps1
    exeDir: true
    wait: true
